version: 0.2  
 
phases:
  pre_build:
    commands:
      - echo PreBuild Started ...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 194606914204.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - mvn clean package
      - echo Building the docker image
      - docker build -t twitter-2065828 .
      - docker tag twitter-2065828:latest 194606914204.dkr.ecr.us-east-1.amazonaws.com/twitter-2065828:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 194606914204.dkr.ecr.us-east-1.amazonaws.com/twitter-2065828:latest
      - echo Writing definition files
      - printf '[{"name":"twitter-2065828","imageUri":"%s"}]' 194606914204.dkr.ecr.us-east-1.amazonaws.com/twitter-2065828:latest > imagedefinition.json
 
artifacts:
  files:
    - imagedefinition.json
